config: 
  plugins: 
    metrics-by-endpoint: {}
  target: 'http://localhost:8000'
  phases: 
    - duration: 20
      arrivalRate: 10
scenarios: 
  - name: 'Sessions Flow (register + login)'
    flow:
      - log: 'Creando un usuario de prueba'
      - get: 
          url: /pruebas/user
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
      - log: 'Registramos el usurio'
      - post: 
          url: /api/sessions/register
          json: 
            first_name: "{{first_name}}"
            last_name: "{{last_name}}"
            email: "{{email}}"
            password: "{{password}}"
      - think: 2
      - log: "login de usuario"
      - post: 
          url: /api/sessions/loggin
          json: 
            email: "{{email}}"
            password: "{{password}}"


